version: '3.1'

services:
  api:
    build:
      context: .
    command: 'bash -c "./gradlew bootRun"'
    working_dir: '/app'
    depends_on:
      - mongo
    volumes:
      - '.:/app'

  mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
